
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Header, TopBar } from "./components/compononts";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div className="w-screen h-screen flex flex-col sm:flex-row ">
          <div className="w-full bg-white sticky top-0 flex sm:hidden">
            <TopBar/>
          </div>
          <div className="hidden sm:block">

        <Header/>
          </div>
          <div className="flex flex-col overflow-x-hidden">

        {children}
          </div>
        </div>
      </body>
    </html>
  );
}
